### ISSUE TITLE
url invalid

### ISSUE THREAD

**Issue by PPJ-SolarTerms** [spring-projects/toolsuite-distribution#6]
hello,
       when mvn install,Invalid repository URL: https://dist.springframework.org/${dist.type}/IDE/nightly/${dist.target.major}.
And i cannot really find it.         thanks

**Comment by martinlippert** [comment]
If you would like to run the build of the project locally on your machine, you need to enable two different profiles:

```
mvn -Pe420 -Psnapshot clean package
```

- `-Pe420` sets the target definition to the latest Eclipse 2021-06 milestone builds
- `-Pe419` sets the target definition to the Eclipse 2021-03 release
- `-Pe418` sets the target definition to the Eclipse 2020-12 release

The snapshot profile is used to determine whether you are building a snapshot, a milestone, or a release build.

**Comment by martinlippert** [comment]
Just keep in mind that you can also download a ready-to-use package from https://github.com/spring-projects/toolsuite-distribution/wiki/Spring-Tool-Suite-3

**Comment by PPJ-SolarTerms** [comment]
Thank you very much for your reply.I can't find version 3.8.3 from  https://github.com/spring-projects/toolsuite-distribution/wiki/Spring-Tool-Suite-3.I have an application scenario that needs to use the mac version 3.8.3.That's why I want to try to buid by my own.

**Comment by martinlippert** [comment]
Hey @PPJ-SolarTerms, here is the download URL of the STS 3.8.3 distribution for Mac:

- on Eclipse 4.6.2: https://dist.springsource.com/release/STS/3.8.3.RELEASE/dist/e4.6/spring-tool-suite-3.8.3.RELEASE-e4.6.2-macosx-cocoa-x86_64.tar.gz
- on Eclipse 4.5.2: https://dist.springsource.com/release/STS/3.8.3.RELEASE/dist/e4.5/spring-tool-suite-3.8.3.RELEASE-e4.5.2-macosx-cocoa-x86_64.tar.gz

Hope this helps!
(but please keep in mind that this old version is not really supported anymore)

**Comment by PPJ-SolarTerms** [comment]
Hey @martinlippert ,my problem has been solved.
Thank you for your helps!
(this is my first time to solve problems through foreign friends)
