### ISSUE TITLE
Looking forward the support of eclipse 4.21 :)

### ISSUE THREAD

**Issue by takeseem** [spring-projects/toolsuite-distribution#7]
Thanks for your help :)
Looking forward to the support of eclipse 4.21 :)

**Comment by martinlippert** [comment]
I updated https://github.com/spring-projects/toolsuite-distribution/wiki/Spring-Tool-Suite-3 to include the latest builds on top of the Eclipse 2021-09 (4.21) release. Please note that these builds are not verified or tested and in minimal maintenance only, we provide them as a convenience only.

Make sure to upgrade your environments to the latest Spring Tools 4 for Eclipse releases (4.12.0.RELEASE at the moment of writing this): https://spring.io/tools

If there is anything that prevents you from upgrading to the latest Spring Tools 4 for Eclipse, please let us know.

**Comment by takeseem** [comment]
Thanks for your job.

it's work:
https://download.springsource.com/release/TOOLS/update/3.9.19.RELEASE/e4.22/

I like the sts3, our some project is old.

**Comment by martinlippert** [comment]
@takeseem Can you be more specific about what you specifically like about STS3 that is not yet in STS4? Would be very interested to hear your thoughts and what it would take to get you with your older projects onto STS4.

**Comment by takeseem** [comment]
@martinlippert thanks for your help, now I using STS4 :)

I install sts4 in eclipse using update site.
1. I found the pom.xml Editor is M2E - POM Editor using LemMinX language server, it's so bad for link to other dependcy.
2. I like the old editor base XML editor ui, so I must be install   M2E - POM Editor (Legacy) using WebTools SourceEditing UI	.

the problem stop I use STS4 the big reason.

but when I direct using STS4 all in one , it's work good, it's not necessary too install M2E - POM Editor (Legacy) using WebTools SourceEditing UI.

details:
https://github.com/eclipse-m2e/m2e-core/issues/608

I have one problem: STS4 all in one not install plugin ` M2E - POM Editor (Legacy) using WebTools SourceEditing UI`
but pom.xml editor is real link to base XML Editor not using Generic Text Editor?

![image](https://user-images.githubusercontent.com/4768523/158480889-8dd1d349-b9b2-4120-b021-cad3e7839bfb.png)
